Vagrant.configure("2") do |config|
  servers=[
    {
      :hostname => "ansible-control",
      :box => "centos/8",
      :ip => "192.168.56.160",
      :ssh_port => '2215'
    },
    {
      :hostname => "Centos1",
      :box => "centos/8",
      :ip => "192.168.56.161",
      :ssh_port => '2250'
    },
    {
      :hostname => "Centos2",
      :box => "centos/8",
      :ip => "192.168.56.162",
      :ssh_port => '2255'
    },
    {
      :hostname => "Centos3",
      :box => "centos/8",
      :ip => "192.168.56.163",
      :ssh_port => '2260'
    },

  ]

  servers.each do |machine|

    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
   
      node.vm.network :private_network, ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"

      node.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 512]
        v.customize ["modifyvm", :id, "--name", machine[:hostname]]
      end
    end
  end

end