---
- hosts: ubuntu 
  become: true
  tasks: 

  - name: install software
    apt:
       name: "{{ packages  }}"
       state: absent
    tags: software

  - name: start apache2 service
    service: 
      name: apache2
      state: restarted
    tags: service