---

- hosts: all
  become: true
  tasks:

  - name: Update && install apache2 and php for ubuntu
    apt:
      name: 
      - apache2
      - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: start apache service
    service:
      name: apache2
      state: started

